### PR TITLE
Text colors & names are insensitive

### PR DESCRIPTION
**Pull request by shadoath**
## Improvements:
 - FontAwesome icons
 - new background set to a galactic night sky 
   - (Would like to have this an updateable option where the user can set URL)
 - Text color can be set

## Fixes
 - {project} names are now cAsE-insensitive

### CODE REVIEW

**Comment by shadoath** [comment]
Looks like this was merged a while back. GitHub said I had changes that this upstream version does not...

**Comment by shadoath** [comment]
@danlister ready for review and merging.

**Comment by danlister** [comment]
Thanks folks 👍

**Comment by danlister** [comment]
Uploaded to the Google Chrome Webstore as v1.4.

**Pull request merged**
