### PR TITLE
Filter by project labels

### PR DESCRIPTION
**Pull request by bastiao**
It can works standalone, but these pull requests, require the #11.

Let me know if you intend individual pull requests

### CODE REVIEW

**Comment by danlister** [comment]
@bastiao Thanks for your pull requests. Where are the label filters displayed?

**Comment by bastiao** [comment]
it's in the top header:

<name of the board> - <organization>  .... "Filter"

Did not work for you?

**Comment by shadoath** [comment]
Is this project being maintained? I would like to update or take over and update.

**Comment by danlister** [comment]
@shadoath Not actively no but feel free to send any Pull Requests and I'll happily review/add them.

**Pull request merged**
