### PR TITLE
Options window moved to extension Popup

### PR DESCRIPTION
**Pull request by shadoath**
Merged #12 #11 
Uses Chrome.sync to keep track of project colors.
View with [?w=1](https://github.com/agebase/projects-for-trello/pull/20/files?w=1)

### CODE REVIEW

**Comment by danlister** [comment]
Thanks @shadoath. I'll get this reviewed over the weekend.

**Comment by shadoath** [comment]
@danlister Got a couple more hands involved.

**Comment by shadoath** [comment]
@danlister Will you be reviewing this soon?

**Comment by danlister** [comment]
Thanks @shadoath @strikemike2k @jreynolds13. Releasing to the Chrome Store now.

**Comment by RiccardoRaccuglia** [comment]
I apologize, but I tried it and label with the same text have different automatic color, and in Chrome extension page I do not see the option link.
image
image

Already I tried to remove this extension and add again

**Comment by danlister** [comment]
@RiccardoRaccuglia You should be able to click on the Projects For Trello icon and view the options there.

screen shot 2017-11-16 at 11 09 03

**Comment by RiccardoRaccuglia** [comment]
Opsh ... Good!

I wish I could set the same color by a prefix text:
TEST% -> yellow
BUG% ->red

**Pull request merged**
